#application.properties

spring.application.name=storybot
#server.port=8089

## Default Profile (comment/uncomment to switch profiles)
## In this currently prod only using and uat need to configure if in high demand
spring.profiles.active=uat
#spring.profiles.active=prod

