package com.siva.storybot.enums;

public enum OwnerIntent {

    GET_USERS, GET_ACTIVE_USERS, GET_EXPIRED_USERS, GET_USER_DETAILS, GET_HISTORY, UPDATE_USER, GLOBAL_TRIAL_ON, GLOBAL_TRIAL_OFF, UNKNOWN
}
